<a href="https://colab.research.google.com/github/yashhhp/All-Chat/blob/master/Arena_Tags_recommendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import requests
import json
import pprint

In [ ]:
headers={"Accept" : "application/vnd.arena+json;version=1"}

In [ ]:
problemAPI="http://arena.siesgst.ac.in/api/problems"

In [ ]:
data=requests.get(problemAPI,headers=headers)

In [ ]:
pprint.pprint(data.json())

[{'_id': '5b5c8cd7276e2200208fed62',
  'code': 'UNI01',
  'contestCode': 'UNIVERSE',
  'name': 'Jumping Rahul',
  'points': 0,
  'tags': []},
 {'_id': '5c39eca03646190022847c54',
  'code': 'UNI02',
  'contestCode': 'UNIVERSE',
  'name': 'Odd or Even',
  'points': 0,
  'tags': ['cakewalk']},
 {'_id': '5c39f0543646190022847c61',
  'code': 'UNI03',
  'contestCode': 'UNIVERSE',
  'name': 'Vowel Shovel',
  'points': 0,
  'tags': ['cakewalk']},
 {'_id': '5c39ed573646190022847c59',
  'code': 'UNI04',
  'contestCode': 'UNIVERSE',
  'name': 'Tug Of War',
  'points': 0,
  'tags': ['cakewalk']},
 {'_id': '5c39f1023646190022847c62',
  'code': 'UNI05',
  'contestCode': 'UNIVERSE',
  'name': 'Distance Finder',
  'points': 0,
  'tags': ['math']},
 {'_id': '5c39f4af80aaed0022b63275',
  'code': 'UNI06',
  'contestCode': 'UNIVERSE',
  'name': 'Time Never Stops',
  'points': 0,
  'tags': ['math', 'strings']},
 {'_id': '5b645f711b2cd40020b6c771',
  'code': 'AUG18A',
  'contestCode': 'AUG18',
  'name': 'Av

In [ ]:
data_json=data.json()

In [ ]:
df_main=pd.json_normalize(data_json)

In [ ]:
df=df_main.copy()

In [ ]:
df.head()

_id             name   code  points contestCode  \
0  5b5c8cd7276e2200208fed62    Jumping Rahul  UNI01       0    UNIVERSE   
1  5c39eca03646190022847c54      Odd or Even  UNI02       0    UNIVERSE   
2  5c39f0543646190022847c61     Vowel Shovel  UNI03       0    UNIVERSE   
3  5c39ed573646190022847c59       Tug Of War  UNI04       0    UNIVERSE   
4  5c39f1023646190022847c62  Distance Finder  UNI05       0    UNIVERSE   

         tags  
0          []  
1  [cakewalk]  
2  [cakewalk]  
3  [cakewalk]  
4      [math]

In [ ]:
df.tail()

_id                 name     code  points  \
200  6335f3dd125f8a00222e06eb  Strategic Hopscotch  B4E22FA     200   
201  6335f8b9125f8a00222e06ec    Prosperous Number  B4E22FB     300   
202  63361b9a125f8a00222e06ef     Horde of Zombies  B4E22FC     250   
203  633620e3fe6e62002205e71e     Flippin switches  B4E22FD     200   
204  6336c0b1f9be3c00226020f2  Find Special Number  B4E22FE     400   

    contestCode                                               tags  
200      B4E22F                                   [array,  matrix]  
201      B4E22F                                             [math]  
202      B4E22F                [multisource bfs,  array,  matrix ]  
203      B4E22F                                            [maths]  
204      B4E22F  [Math,  Two pointer,  String,  Next/Previous l...

In [ ]:
df.drop(["_id","code","points","contestCode"],axis=1,inplace=True)

In [ ]:
df.tail()

name                                               tags
200  Strategic Hopscotch                                   [array,  matrix]
201    Prosperous Number                                             [math]
202     Horde of Zombies                [multisource bfs,  array,  matrix ]
203     Flippin switches                                            [maths]
204  Find Special Number  [Math,  Two pointer,  String,  Next/Previous l...

In [ ]:
df.head()

name        tags
0    Jumping Rahul          []
1      Odd or Even  [cakewalk]
2     Vowel Shovel  [cakewalk]
3       Tug Of War  [cakewalk]
4  Distance Finder      [math]

In [ ]:
def ListToString(arr):
    res=""
    for i in arr:
      res+=" "+i
    return res.lower().strip()

In [ ]:
print(ListToString(["array", "matrix"]))

array matrix


In [ ]:
df["tags"]=df["tags"].map(lambda x : ListToString(x))

In [ ]:
# for i in df.index:
#     tag=(ListToString(df['tags'][i]))
#     df['tags'][i]=tag

In [ ]:
# for i in df.index:
#     tag=df['tags'][i].replace(" ","")
#     df.tags[i]=tag


In [ ]:
df.tail()

name                                               tags
200  Strategic Hopscotch                                      array  matrix
201    Prosperous Number                                               math
202     Horde of Zombies                     multisource bfs  array  matrix
203     Flippin switches                                              maths
204  Find Special Number  math  two pointer  string  next/previous lexic...

In [ ]:
df.head()

name      tags
0    Jumping Rahul          
1      Odd or Even  cakewalk
2     Vowel Shovel  cakewalk
3       Tug Of War  cakewalk
4  Distance Finder      math

In [ ]:
df['tags'].unique()

array(['', 'cakewalk', 'math', 'math strings', 'adhoc strings',
       'adhoc math', 'math sortings', 'strings', 'dp math',
       'graphs strings', 'sortings strings', 'binary search', 'graphs',
       'greedy math', 'dp', 'adhoc', 'adhoc math strings', 'dp strings',
       'heap sortings', 'cakewalk math', 'adhoc cakewalk', 'adhoc dp',
       'adhoc greedy', 'greedy', 'brute force math', 'math number theory',
       'data structures greedy', 'adhoc implementation',
       'adhoc constructive implementation', 'greedy , sorting',
       'greedy  adhoc', 'brute force constructive',
       'implementation, maths', 'greedy,data structures', 'dfs, dsu',
       'adhoc,strings', 'bitwise,math,dp', 'string', 'bruteforce',
       'data structures, greedy', 'adhoc,implementation',
       'sorting greedy', 'maths', 'string, palindrome', 'geometry',
       'mathtag', 'perimeter, math',
       'geometry, math, permutation and combination', 'math  bitwise',
       'brute force, two pointers', 'game

In [ ]:
df["SerialNo"]=df.index
df.head()

name      tags  SerialNo
0    Jumping Rahul                   0
1      Odd or Even  cakewalk         1
2     Vowel Shovel  cakewalk         2
3       Tug Of War  cakewalk         3
4  Distance Finder      math         4

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
cv= CountVectorizer()
count_matrix= cv.fit_transform(df['tags'])

In [ ]:
print(count_matrix)

  (1, 13)	1
  (2, 13)	1
  (3, 13)	1
  (4, 35)	1
  (5, 35)	1
  (5, 58)	1
  (6, 58)	1
  (6, 1)	1
  (7, 35)	1
  (7, 1)	1
  (8, 58)	1
  (8, 1)	1
  (9, 35)	1
  (9, 1)	1
  (10, 58)	1
  (10, 1)	1
  (11, 35)	1
  (11, 56)	1
  (12, 35)	1
  (13, 58)	1
  (14, 35)	1
  (15, 35)	1
  (15, 1)	1
  (16, 35)	1
  (16, 19)	1
  :	:
  (194, 1)	1
  (195, 35)	1
  (195, 43)	1
  (195, 5)	1
  (196, 35)	1
  (197, 36)	1
  (198, 36)	1
  (199, 36)	1
  (200, 6)	1
  (200, 38)	1
  (201, 35)	1
  (202, 6)	1
  (202, 38)	1
  (202, 40)	1
  (202, 7)	1
  (203, 36)	1
  (204, 35)	1
  (204, 57)	1
  (204, 47)	1
  (204, 65)	1
  (204, 49)	1
  (204, 41)	1
  (204, 51)	1
  (204, 32)	1
  (204, 44)	1


In [ ]:
cos_sim= cosine_similarity(count_matrix)
print(cos_sim)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [ ]:
def get_name_from_serialno(serial):
    return df[df.SerialNo==serial]['name'].values[0]

def get_serialno_from_name(name):
    return df[df.name==name]['SerialNo'].values[0]

In [ ]:
prob_user_likes= "Strategic Hopscotch"
prob_serialno= get_serialno_from_name(prob_user_likes)
#print(prob_serialno)
similar_probs= list(enumerate(cos_sim[prob_serialno]))

In [ ]:
sorted_similar_probs= sorted(similar_probs,key= lambda x:x[1], reverse=True)[1:]

In [ ]:
i=0
for element in sorted_similar_probs:
    print(get_name_from_serialno(element[0]))
    i=i+1
    if i>10:
        break

Terrorist bunker
Sort the matrix
Horde of Zombies
Rotation of Matrix
Jumping Rahul
Odd or Even
Vowel Shovel
Tug Of War
Distance Finder
Time Never Stops
Avengers Unite


In [ ]:
arg="Terrorist bunker"

In [ ]:
for i in range(len(df["name"])):
  if df["name"][i]==arg:
    print(df.iloc[i])

name        Terrorist bunker
tags                   array
SerialNo                 170
Name: 170, dtype: object


In [ ]:
df['tags'].replace({"adhoc math": "math","#math":"math",
                     "geometry, math, permutation and combination":'math',
                     "cakewalk math":"math","brute force math":"math","implementation, maths":"math","mathtag":"math",'perimeter, math':"math",'#math #implementation'},inplace=True)